from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 2300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 17, 507, 2071))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameGame = QtWidgets.QFrame(self.layoutWidget)
        self.frameGame.setMinimumSize(QtCore.QSize(504, 550))
        self.frameGame.setMaximumSize(QtCore.QSize(504, 550))
        self.frameGame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGame.setObjectName("frameGame")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frameGame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 511, 511))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnMenu3 = QtWidgets.QPushButton(self.frameGame)
        self.btnMenu3.setGeometry(QtCore.QRect(220, 520, 75, 23))
        self.btnMenu3.setObjectName("btnMenu3")
        self.verticalLayout.addWidget(self.frameGame)
        self.framePlayers = QtWidgets.QFrame(self.layoutWidget)
        self.framePlayers.setMinimumSize(QtCore.QSize(500, 190))
        self.framePlayers.setMaximumSize(QtCore.QSize(500, 190))
        self.framePlayers.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePlayers.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePlayers.setObjectName("framePlayers")
        self.btnOk = QtWidgets.QPushButton(self.framePlayers)
        self.btnOk.setGeometry(QtCore.QRect(60, 140, 112, 32))
        self.btnOk.setObjectName("btnOk")
        self.btnCancel = QtWidgets.QPushButton(self.framePlayers)
        self.btnCancel.setGeometry(QtCore.QRect(360, 140, 112, 32))
        self.btnCancel.setObjectName("btnCancel")
        self.label_4 = QtWidgets.QLabel(self.framePlayers)
        self.label_4.setGeometry(QtCore.QRect(160, -1, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.framePlayers)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 40, 410, 32))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEditX = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditX.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditX.setFont(font)
        self.lineEditX.setObjectName("lineEditX")
        self.horizontalLayout.addWidget(self.lineEditX)
        self.layoutWidget2 = QtWidgets.QWidget(self.framePlayers)
        self.layoutWidget2.setGeometry(QtCore.QRect(60, 90, 410, 32))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.lineEditO = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditO.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditO.setFont(font)
        self.lineEditO.setObjectName("lineEditO")
        self.horizontalLayout_3.addWidget(self.lineEditO)
        self.verticalLayout.addWidget(self.framePlayers)
        self.frameMain = QtWidgets.QFrame(self.layoutWidget)
        self.frameMain.setMinimumSize(QtCore.QSize(504, 200))
        self.frameMain.setMaximumSize(QtCore.QSize(504, 200))
        self.frameMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMain.setObjectName("frameMain")
        self.label = QtWidgets.QLabel(self.frameMain)
        self.label.setGeometry(QtCore.QRect(220, 20, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnNew = QtWidgets.QPushButton(self.frameMain)
        self.btnNew.setGeometry(QtCore.QRect(210, 50, 75, 23))
        self.btnNew.setObjectName("btnNew")
        self.btnRules = QtWidgets.QPushButton(self.frameMain)
        self.btnRules.setGeometry(QtCore.QRect(210, 80, 75, 23))
        self.btnRules.setObjectName("btnRules")
        self.btnRecords = QtWidgets.QPushButton(self.frameMain)
        self.btnRecords.setGeometry(QtCore.QRect(210, 110, 75, 23))
        self.btnRecords.setObjectName("btnRecords")
        self.verticalLayout.addWidget(self.frameMain)
        self.frameRules = QtWidgets.QFrame(self.layoutWidget)
        self.frameRules.setMinimumSize(QtCore.QSize(0, 504))
        self.frameRules.setMaximumSize(QtCore.QSize(16777215, 504))
        self.frameRules.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRules.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRules.setObjectName("frameRules")
        self.label_2 = QtWidgets.QLabel(self.frameRules)
        self.label_2.setGeometry(QtCore.QRect(210, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.labelRules = QtWidgets.QLabel(self.frameRules)
        self.labelRules.setGeometry(QtCore.QRect(16, 50, 481, 281))
        self.labelRules.setText("")
        self.labelRules.setObjectName("labelRules")
        self.btnMenu = QtWidgets.QPushButton(self.frameRules)
        self.btnMenu.setGeometry(QtCore.QRect(210, 400, 75, 23))
        self.btnMenu.setObjectName("btnMenu")
        self.verticalLayout.addWidget(self.frameRules)
        self.frameRecords = QtWidgets.QFrame(self.layoutWidget)
        self.frameRecords.setMinimumSize(QtCore.QSize(505, 505))
        self.frameRecords.setMaximumSize(QtCore.QSize(505, 505))
        self.frameRecords.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRecords.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRecords.setObjectName("frameRecords")
        self.tableView = QtWidgets.QTableView(self.frameRecords)
        self.tableView.setGeometry(QtCore.QRect(10, 40, 491, 411))
        self.tableView.setObjectName("tableView")
        self.label_3 = QtWidgets.QLabel(self.frameRecords)
        self.label_3.setGeometry(QtCore.QRect(200, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btnMenu2 = QtWidgets.QPushButton(self.frameRecords)
        self.btnMenu2.setGeometry(QtCore.QRect(210, 460, 75, 23))
        self.btnMenu2.setObjectName("btnMenu2")
        self.verticalLayout.addWidget(self.frameRecords)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Крестики Нолики"))
        self.btnMenu3.setText(_translate("MainWindow", "Меню"))
        self.btnOk.setText(_translate("MainWindow", "OK"))
        self.btnCancel.setText(_translate("MainWindow", "Отмена"))
        self.label_4.setText(_translate("MainWindow", "Введите имена игроков"))
        self.label_5.setText(_translate("MainWindow", "Крестики"))
        self.label_6.setText(_translate("MainWindow", "Нолики"))
        self.label.setText(_translate("MainWindow", "Меню"))
        self.btnNew.setText(_translate("MainWindow", "Новая игра"))
        self.btnRules.setText(_translate("MainWindow", "Правила"))
        self.btnRecords.setText(_translate("MainWindow", "Рекорды"))
        self.label_2.setText(_translate("MainWindow", "Правила"))
        self.btnMenu.setText(_translate("MainWindow", "Меню"))
        self.label_3.setText(_translate("MainWindow", "Результаты"))
        self.btnMenu2.setText(_translate("MainWindow", "Меню"))
